services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: database

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ./app/backend:/app
    depends_on:
      - db
    container_name: backend

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    restart: always
    container_name: frontend
    volumes:
      - ./app/frontend:/app
    depends_on:
      - backend
