services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: database
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - db
    container_name: django