# Generated by Django 4.1.7 on 2023-03-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
